=== zhukovdm/T1G4/3/xml/schemas/schema-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="https://www.w3.org/2009/01/xml.xsd"/>

    <xs:element name="train">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="electricMotor" type="xs:boolean"/>
                <xs:element name="europeanVehicleNumber" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="bus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="licensePlateNumber" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="vehicle">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="capacity" type="xs:integer"/>
                <xs:element name="consumption" type="xs:integer"/>
                <xs:element name="purchasePrice" type="xs:integer"/>
                <xs:choice>
                    <xs:element ref="bus"/>
                    <xs:element ref="train"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="vehicles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="vehicle" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="producer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="legalName">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="xml:lang" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="vehicles"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="producers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="producer" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== zhukovdm/T1G4/3/xml/data/data-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<producers
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../schemas/schema-2.xsd">

    <producer>
        <id>tatra</id>
        <legalName xml:lang="cs">TATRA TRUCKS a.s.</legalName>
        <vehicles>
            <vehicle>
                <capacity>23</capacity>
                <consumption>42</consumption>
                <purchasePrice>523147</purchasePrice>
                <bus>
                    <id>1</id>
                    <licensePlateNumber>4A2 7983</licensePlateNumber>
                </bus>
            </vehicle>

            <vehicle>
                <capacity>5</capacity>
                <consumption>10</consumption>
                <purchasePrice>65000</purchasePrice>
                <bus>
                    <id>2</id>
                    <licensePlateNumber>5T1 9876</licensePlateNumber>
                </bus>
            </vehicle>

            <vehicle>
                <capacity>123</capacity>
                <consumption>300</consumption>
                <purchasePrice>200000</purchasePrice>
                <train>
                    <id>3</id>
                    <electricMotor>false</electricMotor>
                    <europeanVehicleNumber>EW 40 672</europeanVehicleNumber>
                </train>
            </vehicle>
        </vehicles>
    </producer>

    <producer>
        <id>man</id>
        <legalName xml:lang="de">Maschinenfabrik Augsburg-NÃ¼rnberg</legalName>
        <vehicles>
            <vehicle>
                <capacity>54</capacity>
                <consumption>98</consumption>
                <purchasePrice>123000</purchasePrice>
                <bus>
                    <id>3</id>
                    <licensePlateNumber>6M4 1426</licensePlateNumber>
                </bus>
            </vehicle>
        </vehicles>
    </producer>

    <producer>
        <id>siemens</id>
        <legalName xml:lang="de">Siemens AG</legalName>
        <vehicles>
            <vehicle>
                <capacity>30</capacity>
                <consumption>500</consumption>
                <purchasePrice>550000</purchasePrice>
                <train>
                    <id>1</id>
                    <electricMotor>true</electricMotor>
                    <europeanVehicleNumber>B 228 FK</europeanVehicleNumber>
                </train>
            </vehicle>
        </vehicles>
    </producer>

    <producer>
        <id>bombardier</id>
        <legalName xml:lang="en">Bombardier Inc.</legalName>
        <vehicles>
            <vehicle>
                <capacity>100</capacity>
                <consumption>1000</consumption>
                <purchasePrice>1000000</purchasePrice>
                <train>
                    <id>2</id>
                    <electricMotor>true</electricMotor>
                    <europeanVehicleNumber>CGI 964</europeanVehicleNumber>
                </train>
            </vehicle>
        </vehicles>
    </producer>

</producers>
